pyinstaller -F -w beihai.py
pyinstaller -F -w chongqingbeibei.py
pyinstaller -F -w chongzhou.py
pyinstaller -F -w guanshanhu.py
pyinstaller -F -w huimin.py
pyinstaller -F -w huzhou.py
pyinstaller -F -w huzhou_default.py
pyinstaller -F -w jiangmen.py
pyinstaller -F -w jinhua.py
pyinstaller -F -w jixi.py
pyinstaller -F -w liaoyang.py
pyinstaller -F -w liupanshui.py
pyinstaller -F -w liupanshui_default.py
pyinstaller -F -w nanningjiangnan.py
pyinstaller -F -w ningde.py
pyinstaller -F -w pingyang.py
pyinstaller -F -w pingyang_hui.py
pyinstaller -F -w quzhou.py
pyinstaller -F -w sanming.py
pyinstaller -F -w shenyangxitie.py
pyinstaller -F -w shenyangxitie_default.py
pyinstaller -F -w taizhou.py
pyinstaller -F -w xishuangbanna.py
pyinstaller -F -w zhangzhoutaishang.py