pyinstaller -F beihai.py -p yima.py
pyinstaller -F chongqingbeibei.py -p yima.py
pyinstaller -F chongzhou.py -p yima.py
pyinstaller -F dalianganjingzi_xinrenli.py -p yima.py
pyinstaller -F guanshanhu.py -p yima.py
pyinstaller -F huimin.py -p yima.py
pyinstaller -F huzhou.py -p yima.py
pyinstaller -F huzhou_xinrenli.py -p yima.py
pyinstaller -F jiangmen.py -p yima.py
pyinstaller -F jinhua.py -p yima.py
pyinstaller -F jixi.py -p yima.py
pyinstaller -F liaoyang.py -p yima.py
pyinstaller -F liupanshui.py -p yima.py
pyinstaller -F liupanshui_xinrenli.py -p yima.py
pyinstaller -F nanningjiangnan.py -p yima.py
pyinstaller -F ningde.py -p yima.py
pyinstaller -F pingyang.py -p yima.py
pyinstaller -F pingyang_hui.py -p yima.py
pyinstaller -F quzhou.py -p yima.py
pyinstaller -F sanming.py -p yima.py
pyinstaller -F sanming_xinrenli.py -p yima.py
pyinstaller -F shenyangtiexi.py -p yima.py
pyinstaller -F shenyangtiexi_xinrenli.py -p yima.py
pyinstaller -F taizhou.py -p yima.py
pyinstaller -F wuhai.py -p yima.py
pyinstaller -F wuhai_xinrenli.py -p yima.py
pyinstaller -F xishuangbanna.py -p yima.py
pyinstaller -F zhangzhoutaishang.py -p yima.py