pyinstaller -F beijinghuaifang_wai.py
pyinstaller -F chongqingbeipei_wai.py
pyinstaller -F huiminqu_wai.py
pyinstaller -F kunmingxishan_wai.py
pyinstaller -F qingdaolicang_wai.py
pyinstaller -F sanming_wai.py
pyinstaller -F taizhou_wai.py
pyinstaller -F tongliao_wai.py
pyinstaller -F wuhai_wai.py