pyinstaller -F binzhou.py
pyinstaller -F chongqingbeibei.py
pyinstaller -F dalianganjingzi.py
pyinstaller -F guanshanhu.py
pyinstaller -F jingmen.py
pyinstaller -F jinzhou.py
pyinstaller -F jixi.py
pyinstaller -F liupanshui.py
pyinstaller -F luzhou.py
pyinstaller -F pingyang.py
pyinstaller -F qingdaolicang.py
pyinstaller -F yancheng.py
pyinstaller -F yiyang.py