pyinstaller -F baotou.py
pyinstaller -F beihai.py
pyinstaller -F binzhou.py
pyinstaller -F chengduqingyang.py
pyinstaller -F chongqingbeibei.py
pyinstaller -F chongzhou.py
pyinstaller -F dalianganjingzi.py
pyinstaller -F guanshanhu.py
pyinstaller -F huimin.py
pyinstaller -F uzhou.py
pyinstaller -F jiangmen.py
pyinstaller -F inhua.py
pyinstaller -F ixi.py
pyinstaller -F unmingxishan.py
pyinstaller -F iaoyang.py
pyinstaller -F iupanshui.py
pyinstaller -F anningjiangnan.py
pyinstaller -F ingde.py
pyinstaller -F ingyang.py
pyinstaller -F uzhou.py
pyinstaller -F anming.py
pyinstaller -F henyangtiexi.py
pyinstaller -F aizhou.py
pyinstaller -F uhai.py
pyinstaller -F uhai_wai.py
pyinstaller -F ishuangbanna.py
pyinstaller -F iyang.py
pyinstaller -F hangzhoutaishang.py