pyinstaller -F baotou.py
pyinstaller -F beihai.py
pyinstaller -F binzhou.py
pyinstaller -F chengduqingyang.py
pyinstaller -F chongqingbeibei.py
pyinstaller -F chongzhou.py
pyinstaller -F dalianganjingzi.py
pyinstaller -F guanshanhu.py
pyinstaller -F huaibei.py
pyinstaller -F huzhou.py
pyinstaller -F jiangmen.py
pyinstaller -F jinhua.py
pyinstaller -F jinzhou.py
pyinstaller -F jixi.py
pyinstaller -F liaoyang.py
pyinstaller -F liupanshui.py
pyinstaller -F luzhou.py
pyinstaller -F nanningjiangnan.py
pyinstaller -F ningde.py
pyinstaller -F pingyang.py
pyinstaller -F qingdaolicang.py
pyinstaller -F quzhou.py
pyinstaller -F shenyangtiexi.py
pyinstaller -F xishuangbanna.py
pyinstaller -F yiyang.py
pyinstaller -F zhangzhoutaishang.py