pyinstaller -F baotou_scan.py
pyinstaller -F beijingfengtai_scan.py
pyinstaller -F beijinghuaifang_scan.py
pyinstaller -F binzhou_scan.py
pyinstaller -F chengduqingyang_scan.py
pyinstaller -F dalianganjingzi_scan.py
pyinstaller -F dandong_scan.py
pyinstaller -F guanshanhu_scan.py
pyinstaller -F huiminqu_scan.py
pyinstaller -F huzhou_scan.py
pyinstaller -F jinzhou_scan.py
pyinstaller -F jixi_scan.py
pyinstaller -F kunmingxishan_scan.py
pyinstaller -F liupanshui_scan.py
pyinstaller -F pingyang_scan.py
pyinstaller -F qingdaolicang_scan.py
pyinstaller -F quzhou_scan.py
pyinstaller -F sanming_scan.py
pyinstaller -F shenyangtiexi_scan.py
pyinstaller -F taizhou_scan.py
pyinstaller -F tongliao_scan.py
pyinstaller -F wuhai_scan.py
pyinstaller -F yiyang_scan.py